# Site settings
title: Shemss
email: shemss@gmail.com
description: >
  Awesome construction company in Lake Tahoe
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shemss.com" # the base hostname & protocol for your site

social:
  facebook: https://www.facebook.com/shemssinc
  twitter: https://twitter.com/SHEMSSinc
  youtube: https://www.youtube.com/user/SHEMSSconstruction
  google-plus: https://plus.google.com/108316022689360703562/posts
  pinterest: http://www.pinterest.com/sergshemyakin/

nav:
- title: Services
  subtitle: Builders
  url: /services/
- title: Projects
  subtitle: Gallery of Our Work
  url: /projects/
- title: About
  subtitle: Our Approach
  url: /about/
- title: Resources
  subtitle: Educated Choices
  url: /resources
- title: Contact
  subtitle: Get in Touch
  url: /contact/

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock]

gems:
  - jekyll-assets
  - jekyll-assets/bootstrap
  - jekyll-sitemap

assets:
  js_compressor:  uglifier
  css_compressor: sass
