# Site settings
title: Shemss
email: shemss@gmail.com
description: >
  Awesome construction company in Lake Tahoe
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://shemss.com" # the base hostname & protocol for your site

nav:
- title: Services
  subtitle: Builders
  url: /services/
- title: Projects
  subtitle: Gallery of Our Work
  url: /projects/
- title: About
  subtitle: Our Approach
  url: /about/
- title: Contact
  subtitle: Get in Touch
  url: /contact/

# Build settings
markdown: kramdown
exclude: [Gemfile, Gemfile.lock]

gems:
  - jekyll-assets
  - jekyll-assets/bootstrap
  - jekyll-sitemap

assets:
  js_compressor:  uglifier
  css_compressor: sass
